require "user.options"
require "user.plugins"
require "user.lspInstaller"
require "user.cmp"
require "user.gitsigns"
require "user.colorscheme"
require "user.treesitter"
require "user.keymaps"
require "user.nvim-tree"
require "user.galaxyline"

